/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.eduTech.gui;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import mx.itson.eduTech.entidades.Alumno;
import mx.itson.eduTech.entidades.Maestro;
import mx.itson.eduTech.negocio.AlumnoNegocio;
import mx.itson.eduTech.negocio.MaestroNegocio;
import mx.itson.eduTech.persistencia.AlumnoPersistencia;
import mx.itson.eduTech.persistencia.MaestroPersistencia;

/**
 * @author Daniel Solano, Valeria García, Jesús Torres.
 */
public class Principal extends javax.swing.JFrame {

    public static Alumno alumno = new Alumno();
    public static Maestro maestro = new Maestro();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        desactivarTodo();
        iniciarSesion();
        setColor(jLabel8);
        resetColor(jLabel10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        txtContrasenaIniciar = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnCrearcuenta = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        lbBlueAlumno = new javax.swing.JLabel();
        lbBlueInstructor = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbWhiteInstructor = new javax.swing.JLabel();
        lbWhiteAlumno = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCorre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 49, 114));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setBackground(new java.awt.Color(30, 86, 160));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 440, 10));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(30, 86, 160));
        jLabel17.setText("Contraseña");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, -1, -1));

        txtContrasenaIniciar.setBackground(new java.awt.Color(246, 246, 246));
        txtContrasenaIniciar.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        txtContrasenaIniciar.setForeground(new java.awt.Color(30, 86, 160));
        txtContrasenaIniciar.setText("Introduce tu contraseña");
        txtContrasenaIniciar.setBorder(null);
        txtContrasenaIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(txtContrasenaIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 440, 40));

        btnIniciarSesion.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar");
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.setContentAreaFilled(false);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 540, 110, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/buttonimg.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 540, -1, -1));

        btnCrearcuenta.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        btnCrearcuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearcuenta.setText("Crear");
        btnCrearcuenta.setBorder(null);
        btnCrearcuenta.setContentAreaFilled(false);
        btnCrearcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearcuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 620, 110, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/buttonimg.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 620, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(30, 86, 160));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 402, 440, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/panel2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1317, 0, 50, 730));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Instructor ");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 110, 40));

        jSeparator2.setBackground(new java.awt.Color(30, 86, 160));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 440, 10));

        jLabel14.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Alumno");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, 110, 40));

        lbBlueAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/buttonimg.png"))); // NOI18N
        jPanel1.add(lbBlueAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, -1, 40));

        lbBlueInstructor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/buttonimg.png"))); // NOI18N
        jPanel1.add(lbBlueInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 110, 40));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(214, 228, 240));
        jLabel8.setText("Iniciar sesión");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel9.setText("O");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(214, 228, 240));
        jLabel10.setText("Crear cuenta");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/open-book 128.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 180, 130));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 66)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(246, 246, 246));
        jLabel4.setText("tech");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, 70));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 66)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(246, 246, 246));
        jLabel5.setText("edu");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, 70));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(246, 246, 246));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Learn in everywhere.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 160, 40));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 246, 246));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Learn together.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 160, 30));

        lbWhiteInstructor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/buttonimgdes.png"))); // NOI18N
        jPanel1.add(lbWhiteInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 110, 40));

        lbWhiteAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/buttonimgdes.png"))); // NOI18N
        jPanel1.add(lbWhiteAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, -1, 40));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(30, 86, 160));
        jLabel11.setText("Nombre completo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, -1, -1));

        txtNombre.setBackground(new java.awt.Color(246, 246, 246));
        txtNombre.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(30, 86, 160));
        txtNombre.setText("Introduce tu nombre completo");
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 440, 40));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(30, 86, 160));
        jLabel13.setText("Dirección de correo electrónico");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, -1, -1));

        txtCorre.setBackground(new java.awt.Color(246, 246, 246));
        txtCorre.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        txtCorre.setForeground(new java.awt.Color(30, 86, 160));
        txtCorre.setText("Introduce tu correo electrónico");
        txtCorre.setBorder(null);
        txtCorre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorre, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 440, 40));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(30, 86, 160));
        jLabel15.setText("Contraseña");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, -1, -1));

        txtContrasena.setBackground(new java.awt.Color(246, 246, 246));
        txtContrasena.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(30, 86, 160));
        txtContrasena.setText("Introduce tu contraseña");
        txtContrasena.setBorder(null);
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 440, 40));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(30, 86, 160));
        jLabel16.setText("Correo electrónico");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(246, 246, 246));
        txtCorreo.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(30, 86, 160));
        txtCorreo.setText("Introduce tu correo electrónico");
        txtCorreo.setBorder(null);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 440, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/panel2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, 730));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtContrasenaIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaIniciarActionPerformed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:
        activarInstructor();
        lbBlueAlumno.setVisible(false);
        lbWhiteAlumno.setVisible(true);

        //Se puede obtener por medio de un parametro o algo así.
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        // TODO add your handling code here:
        activarAlumno();
        lbBlueInstructor.setVisible(false);
        lbWhiteInstructor.setVisible(true);

        //Se pasan los valores del alumno por un parametro.
    }//GEN-LAST:event_jLabel14MousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
        setColor(jLabel8);
        resetColor(jLabel10);
        desactivarTodo();
        iniciarSesion();


    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
        setColor(jLabel10);
        resetColor(jLabel8);
        desactivarTodo();
        crearCuenta();
    }//GEN-LAST:event_jLabel10MousePressed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed

        MaestroPersistencia mp = new MaestroPersistencia();
        AlumnoPersistencia aP = new AlumnoPersistencia();
        String correo = txtCorreo.getText();
        String contrasena = txtContrasenaIniciar.getText();

        alumno = aP.obtenerPorCorreoContrasena(correo, contrasena);
        maestro = mp.obtenerPorCorreoContrasena(correo, contrasena);
        if (alumno != null) {
            this.dispose();
            new PrincipalAlumno().setVisible(true);
        } else {
            if (maestro != null) {
                this.dispose();
                new PrincipalMaestro().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Correo o contraseña incorrecta, verifique.");
            }
        }

    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * Metodo que permite verificar el formato correcto del email.
     * @param correo El correo a verificar.
     * @return El valor booleano.
     */
    public boolean verificarEmail(String correo) {
        String patternEmail = "[_A-Za-z0-9-\\+]+(\\.[A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern pattern = Pattern.compile(patternEmail);
        Matcher matcher = pattern.matcher(correo);
        return matcher.matches();
    }

    /**
     * Metodo que permite limpiar las cajas de texto.
     */
    public void limpiarCrear(){
        txtContrasena.setText("");
        txtCorre.setText("");
        txtNombre.setText("");
    }
    
    private void btnCrearcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearcuentaActionPerformed
        MaestroNegocio mn = new MaestroNegocio();
        AlumnoNegocio an = new AlumnoNegocio();
        String nombre = txtNombre.getText();
        String correo = txtCorre.getText();
        String contrasena = txtContrasena.getText();
        if (verificarEmail(correo)) {
            if (lbBlueAlumno.isVisible() && !lbBlueInstructor.isVisible()) {
                Alumno al = new Alumno(0, nombre, correo, contrasena);
                if (an.verificarUsuario(al.getCorreo()) && mn.verificarUsuario(al.getCorreo())) {
                    int i = an.guardar(al);
                    if (i != -1) {
                        JOptionPane.showMessageDialog(this, "Se ha registrado correctamente");
                        limpiarCrear();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Ya existe un usuario registrado con este correo");
                }
            } else {
                if (lbBlueInstructor.isVisible() && !lbBlueAlumno.isVisible()) {
                    Maestro m = new Maestro(0, nombre, correo, contrasena);
                    if (mn.verificarUsuario(m.getCorreo()) && an.verificarUsuario(m.getCorreo())) {
                        int id = mn.guardar(m);
                        if (id != -1) {
                            JOptionPane.showMessageDialog(this, "Se ha registrado correctamente");
                            limpiarCrear();
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Ya existe un usuario registrado con este correo");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Seleccione el tipo de cuenta a crear");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un correo válido");
        }

    }//GEN-LAST:event_btnCrearcuentaActionPerformed

    /**
     * Metodo que permite activar la opcion de alumno.
     */
    public void activarAlumno() {
        lbBlueAlumno.setVisible(true);
        lbWhiteAlumno.setVisible(false);

    }
    /**
     * Metodo que permite activar la opcion de instructor.
     */
    public void activarInstructor() {
        lbBlueInstructor.setVisible(true);
        lbWhiteInstructor.setVisible(false);
    }

    /**
     * Metodo que permite desactivar todas las cajas de texto.
     */
    public void desactivarTodo() {
        btnIniciarSesion.setVisible(false);
        jLabel19.setVisible(false);
        txtCorreo.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        txtContrasenaIniciar.setVisible(false);
        lbBlueInstructor.setVisible(false);
        lbWhiteInstructor.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        lbBlueAlumno.setVisible(false);
        lbWhiteAlumno.setVisible(false);
        jLabel14.setVisible(false);
        jLabel11.setVisible(false);
        jLabel15.setVisible(false);
        txtCorre.setVisible(false);
        txtNombre.setVisible(false);
        txtContrasena.setVisible(false);
        jLabel18.setVisible(false);
        btnCrearcuenta.setVisible(false);
        jSeparator2.setVisible(false);
        jSeparator4.setVisible(false);
        jSeparator5.setVisible(false);

    }

    /**
     * Metodo que permite activar la opcion de alumno.
     */
    public void iniciarSesion() {
        btnIniciarSesion.setVisible(true);
        jLabel19.setVisible(true);
        txtCorreo.setVisible(true);
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        txtContrasenaIniciar.setVisible(true);
        jSeparator5.setVisible(true);
        jSeparator4.setVisible(true);
    }

    /**
     * Metodo que permite activar las cajas de texto para crear una cuenta.
     */
    public void crearCuenta() {
        lbBlueInstructor.setVisible(true);
        lbWhiteInstructor.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        lbBlueAlumno.setVisible(true);
        lbWhiteAlumno.setVisible(true);
        jLabel14.setVisible(true);
        jLabel11.setVisible(true);
        jLabel15.setVisible(true);
        txtCorre.setVisible(true);
        txtNombre.setVisible(true);
        txtContrasena.setVisible(true);
        jLabel18.setVisible(true);
        btnCrearcuenta.setVisible(true);
        jSeparator2.setVisible(true);
        jSeparator4.setVisible(true);
        jSeparator5.setVisible(true);
    }
/**
 * Metodo que permite resetear el color.
 * @param label Label que se necesita resetear el color.
 */
    public void resetColor(JLabel label) {
        label.setForeground(new Color(214, 228, 240));
    }
/**
 * Metodo que permite resetear el color.
 * @param label Label que se necesita resetear el color.
 */
    public void setColor(JLabel label) {
        label.setForeground(new Color(22, 49, 114));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearcuenta;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbBlueAlumno;
    private javax.swing.JLabel lbBlueInstructor;
    private javax.swing.JLabel lbWhiteAlumno;
    private javax.swing.JLabel lbWhiteInstructor;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtContrasenaIniciar;
    private javax.swing.JTextField txtCorre;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
