/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.eduTech.gui;

import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.eduTech.entidades.Curso;
import mx.itson.eduTech.entidades.CursoAlumno;
import mx.itson.eduTech.entidades.Tarea;
import static mx.itson.eduTech.gui.Principal.alumno;
import static mx.itson.eduTech.gui.Principal.maestro;
import mx.itson.eduTech.negocio.CursoAlumnoNegocio;
import mx.itson.eduTech.negocio.CursoNegocio;
import mx.itson.eduTech.negocio.TareaNegocio;

/**
 * @author Daniel Solano, Valeria García, Jesús Torres.
 */
public class PrincipalAlumno extends javax.swing.JFrame {

    public DefaultTableModel modelo1, modelo2;
    public DefaultComboBoxModel cbModel;

    /**
     * Creates new form PrincipalAlumno
     */
    public PrincipalAlumno() {
        initComponents();
        panelCursos.setVisible(false);
        panelCursosDisponibles.setVisible(false);
        lbNombreUsuario.setText(alumno.getNombre());
        tbTareas.getColumnModel().getColumn(0).setMaxWidth(0);
        tbTareas.getColumnModel().getColumn(0).setMinWidth(0);
        tbTareas.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tbTareas.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tbTareas.getColumnModel().getColumn(2).setMaxWidth(0);
        tbTareas.getColumnModel().getColumn(2).setMinWidth(0);
        tbTareas.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(0);
        tbTareas.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
        tbCursos.getColumnModel().getColumn(0).setMaxWidth(0);
        tbCursos.getColumnModel().getColumn(0).setMinWidth(0);
        tbCursos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tbCursos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        cargarCursos();
    }

    /**
     * Metodo que permite cargar los cursos que tiene el alumno.
     */
    public void cargarCursos() {
        CursoAlumnoNegocio can = new CursoAlumnoNegocio();
        TareaNegocio tn = new TareaNegocio();
        CursoNegocio cn =new CursoNegocio();
        List<CursoAlumno> cursos = can.obtenerCursosPorAlumno(alumno.getId());
        if (!cursos.isEmpty()) {
            modelo1 = (DefaultTableModel) tbCursos.getModel();
            modelo2 = (DefaultTableModel) tbTareas.getModel();
            modelo1.getDataVector().clear();
            modelo2.getDataVector().clear();
            for (CursoAlumno ca : cursos) {
                Curso c=cn.obtenerPorId(ca.getIdCurso());
                modelo1.addRow(new Object[]{
                    c.getId(),
                    c.getNombre()
                });
                if (!c.getTareas().isEmpty()) {
                    for (Tarea t : c.getTareas()) {
                        modelo2.addRow(new Object[]{
                            t.getId(),
                            t.getNombre(),
                            c.getId()
                        });
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNombreUsuario = new javax.swing.JLabel();
        lbRow1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbRow = new javax.swing.JLabel();
        lbCursos = new javax.swing.JLabel();
        lbInicio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTareas = new win8.swing.MetroTableUI();
        panelCursos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCursos = new win8.swing.MetroTableUI();
        btnUnirseGrupo1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        panelCursosDisponibles = new javax.swing.JPanel();
        btnUnirseGrupo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbCursos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNombreUsuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lbNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreUsuario.setText("Nombre del usuario");
        jPanel1.add(lbNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 230, 70));

        lbRow1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lbRow1.setForeground(new java.awt.Color(255, 255, 255));
        lbRow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/sort-down16.png"))); // NOI18N
        lbRow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbRow1MousePressed(evt);
            }
        });
        jPanel1.add(lbRow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 70, 70));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 86, 160));
        jLabel6.setText("Mis tareas");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 80, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/cabecera-tabla.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 70, 310, 50));

        lbRow.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lbRow.setForeground(new java.awt.Color(255, 255, 255));
        lbRow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/sort-down16.png"))); // NOI18N
        lbRow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbRowMousePressed(evt);
            }
        });
        jPanel1.add(lbRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 30, 60));

        lbCursos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lbCursos.setForeground(new java.awt.Color(255, 255, 255));
        lbCursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCursos.setText("Cursos");
        lbCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCursosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbCursosMouseReleased(evt);
            }
        });
        jPanel1.add(lbCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 190, 70));

        lbInicio.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lbInicio.setForeground(new java.awt.Color(255, 255, 255));
        lbInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInicio.setText("Inicio");
        lbInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbInicioMousePressed(evt);
            }
        });
        jPanel1.add(lbInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 190, 70));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(246, 246, 246));
        jLabel4.setText("tech");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 70));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(246, 246, 246));
        jLabel5.setText("edu");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/open-book 32.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/barras-EduTec.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 70));

        tbTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Tarea", "idCurso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTareas.setRowHeight(40);
        tbTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTareasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTareas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, 320, 660));

        panelCursos.setBackground(new java.awt.Color(255, 255, 255));
        panelCursos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 86, 160));
        jLabel7.setText("Cursos");
        panelCursos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/cabecera-tabla.png"))); // NOI18N
        panelCursos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 50));

        tbCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Cursos"
            }
        ));
        jScrollPane2.setViewportView(tbCursos);

        panelCursos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 300, 210));

        btnUnirseGrupo1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        btnUnirseGrupo1.setForeground(new java.awt.Color(255, 255, 255));
        btnUnirseGrupo1.setText("Unirse");
        btnUnirseGrupo1.setBorder(null);
        btnUnirseGrupo1.setContentAreaFilled(false);
        btnUnirseGrupo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseGrupo1ActionPerformed(evt);
            }
        });
        panelCursos.add(btnUnirseGrupo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 110, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/buttonimg.png"))); // NOI18N
        panelCursos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jPanel1.add(panelCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 360, 290));

        panelCursosDisponibles.setBackground(new java.awt.Color(255, 255, 255));
        panelCursosDisponibles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUnirseGrupo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        btnUnirseGrupo.setForeground(new java.awt.Color(255, 255, 255));
        btnUnirseGrupo.setText("Unirse");
        btnUnirseGrupo.setBorder(null);
        btnUnirseGrupo.setContentAreaFilled(false);
        btnUnirseGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseGrupoActionPerformed(evt);
            }
        });
        panelCursosDisponibles.add(btnUnirseGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 110, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/buttonimg.png"))); // NOI18N
        panelCursosDisponibles.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(30, 86, 160));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelCursosDisponibles.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 110, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/buttonimgdes.png"))); // NOI18N
        panelCursosDisponibles.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("Cursos disponibles:");
        panelCursosDisponibles.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));
        panelCursosDisponibles.add(cbCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 240, 30));

        jPanel1.add(panelCursosDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 410, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInicioMousePressed
        this.dispose();
        PrincipalAlumno p = new PrincipalAlumno();
        p.setVisible(true);
    }//GEN-LAST:event_lbInicioMousePressed

    private void lbCursosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCursosMousePressed
        // TODO add your handling code here:
        cargarCursos();
        panelCursos.setVisible(true);

    }//GEN-LAST:event_lbCursosMousePressed

    private void lbRowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRowMousePressed
        // TODO add your handling code here:
        panelCursos.setVisible(false);
    }//GEN-LAST:event_lbRowMousePressed

    private void lbCursosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCursosMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_lbCursosMouseReleased

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        panelCursosDisponibles.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Metodo que permite cargar los cursos disponibles para ingresar.
     */
    public void cargarCursosDisponibles(){
        CursoAlumnoNegocio can = new CursoAlumnoNegocio();
        List<Curso> cursos = can.obtenerCursosDisponibles(alumno.getId());
        if (cursos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay cursos disponibles");
        } else {
            cbModel=(DefaultComboBoxModel) cbCursos.getModel();
            cbModel.removeAllElements();
            for(Curso c : cursos){
                cbModel.addElement(c);
            }
            panelCursos.setVisible(false);
            panelCursosDisponibles.setVisible(true);
        }
    }
    private void btnUnirseGrupo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseGrupo1ActionPerformed
        cargarCursosDisponibles();
    }//GEN-LAST:event_btnUnirseGrupo1ActionPerformed

    private void btnUnirseGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseGrupoActionPerformed
        Curso c=(Curso) cbCursos.getSelectedItem();
        CursoAlumnoNegocio can= new CursoAlumnoNegocio();
        CursoAlumno ca = new CursoAlumno(0, alumno.getId(), c.getId());
        int id=can.guardar(ca);
        if(id!=-1){
            JOptionPane.showMessageDialog(this, "Se unió al curso");
            panelCursos.setVisible(false);
            panelCursosDisponibles.setVisible(false);
        }
    }//GEN-LAST:event_btnUnirseGrupoActionPerformed
static Tarea tarea;
static Curso curso;
    private void tbTareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTareasMouseClicked
        int fila=tbTareas.getSelectedRow();
        if(fila!=-1){
            modelo1=(DefaultTableModel) tbTareas.getModel();
            TareaNegocio tn = new TareaNegocio();
            CursoNegocio cn = new CursoNegocio();
            int id =(int) modelo1.getValueAt(fila, 0);
            int idCurso=(int) modelo1.getValueAt(fila,2);
            tarea=tn.obtenerPorId(id);
            curso=cn.obtenerPorId(idCurso);
            this.dispose();
            new TareaAlumno().setVisible(true);
        }
    }//GEN-LAST:event_tbTareasMouseClicked

    private void lbRow1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRow1MousePressed
        alumno=null;
        maestro=null;
        this.dispose();
        new Principal().setVisible(true);
        
    }//GEN-LAST:event_lbRow1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnUnirseGrupo;
    private javax.swing.JButton btnUnirseGrupo1;
    private javax.swing.JComboBox<Curso> cbCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCursos;
    private javax.swing.JLabel lbInicio;
    private javax.swing.JLabel lbNombreUsuario;
    private javax.swing.JLabel lbRow;
    private javax.swing.JLabel lbRow1;
    private javax.swing.JPanel panelCursos;
    private javax.swing.JPanel panelCursosDisponibles;
    private win8.swing.MetroTableUI tbCursos;
    private win8.swing.MetroTableUI tbTareas;
    // End of variables declaration//GEN-END:variables
}
