/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.eduTech.gui;

/**
 *
 * @author Valeria
 */
public class TareaMaestro extends javax.swing.JFrame {

    /**
     * Creates new form TareaAlumno
     */
    public TareaMaestro() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lbRow1 = new javax.swing.JLabel();
        lbRow = new javax.swing.JLabel();
        lbCursos = new javax.swing.JLabel();
        lbInicio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        metroTableUI1 = new win8.swing.MetroTableUI();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbNombreAsignacion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbFechaAsignacion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbDescripcionTarea = new javax.swing.JLabel();
        lbDescripcionTarea1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre del usuario");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, -1, 70));

        lbRow1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lbRow1.setForeground(new java.awt.Color(255, 255, 255));
        lbRow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/sort-down16.png"))); // NOI18N
        lbRow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbRow1MousePressed(evt);
            }
        });
        jPanel1.add(lbRow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 30, 70));

        lbRow.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lbRow.setForeground(new java.awt.Color(255, 255, 255));
        lbRow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/sort-down16.png"))); // NOI18N
        lbRow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbRowMousePressed(evt);
            }
        });
        jPanel1.add(lbRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 30, 60));

        lbCursos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lbCursos.setForeground(new java.awt.Color(255, 255, 255));
        lbCursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCursos.setText("Cursos");
        lbCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCursosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbCursosMouseReleased(evt);
            }
        });
        jPanel1.add(lbCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 190, 70));

        lbInicio.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lbInicio.setForeground(new java.awt.Color(255, 255, 255));
        lbInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInicio.setText("Inicio");
        lbInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbInicioMousePressed(evt);
            }
        });
        jPanel1.add(lbInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 190, 70));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(246, 246, 246));
        jLabel4.setText("tech");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 70));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(246, 246, 246));
        jLabel5.setText("edu");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/open-book 32.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/barras-EduTec.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 86, 160));
        jLabel10.setText("Entregas");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1059, 230, 100, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/cabecera-tabla.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 230, 300, 60));

        metroTableUI1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tareas"
            }
        ));
        jScrollPane1.setViewportView(metroTableUI1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 230, 320, 500));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/folder32.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 40, 40));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setText("Nombre de la materia");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 170, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/eduTech/imagenes/titulo-tarea.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1370, 70));

        lbNombreAsignacion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        lbNombreAsignacion.setText("Nombre de la asignación");
        jPanel1.add(lbNombreAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(246, 246, 246));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 1300, 10));

        lbFechaAsignacion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lbFechaAsignacion.setText("Fecha");
        jPanel1.add(lbFechaAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(246, 246, 246));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 960, -1));

        lbDescripcionTarea.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lbDescripcionTarea.setText("Fecha en la que se posteo la tarea");
        jPanel1.add(lbDescripcionTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        lbDescripcionTarea1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lbDescripcionTarea1.setText("Descripción de la tarea");
        jPanel1.add(lbDescripcionTarea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 690, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInicioMousePressed
        // TODO add your handling code here:
        PrincipalAlumno p = new PrincipalAlumno();
        p.setVisible(true);
    }//GEN-LAST:event_lbInicioMousePressed

    private void lbCursosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCursosMousePressed
        // TODO add your handling code here:

     

    }//GEN-LAST:event_lbCursosMousePressed

    private void lbCursosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCursosMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_lbCursosMouseReleased

    private void lbRowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRowMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbRowMousePressed

    private void lbRow1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRow1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbRow1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TareaMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TareaMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TareaMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TareaMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TareaMaestro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbCursos;
    private javax.swing.JLabel lbDescripcionTarea;
    private javax.swing.JLabel lbDescripcionTarea1;
    private javax.swing.JLabel lbFechaAsignacion;
    private javax.swing.JLabel lbInicio;
    private javax.swing.JLabel lbNombreAsignacion;
    private javax.swing.JLabel lbRow;
    private javax.swing.JLabel lbRow1;
    private win8.swing.MetroTableUI metroTableUI1;
    // End of variables declaration//GEN-END:variables
}
